### ISSUE TITLE
Extend Page Navigation bar with manual page input

### ISSUE THREAD

**Issue by dsanko-sc** [OpusCapita/react-reference-select#25]
# Todo
Input for page and button with text 'Go' (in English) should be added to the right of current page navigation.
It will look like this:
![pagination4](https://user-images.githubusercontent.com/25082620/38082082-489cb39c-334e-11e8-942a-cb873c7f2c9d.png)
Input behaviour:
1. Action: We enter number in range from '1' to max page number then press key 'Enter' on keyboard or button 'Go'
Result: Current page is entered value, input is clear
2. Action: We enter number less than '1' then press key 'Enter' on keyboard or button 'Go'
Result: Current page is not changed, input is clear
3. Action: We enter number more then max page number then press key 'Enter' on keyboard or button 'Go'
Result: Current page is max page number, input is clear
4. Action: We enter value which contains non-numeric symbols then press key 'Enter' on keyboard or button 'Go'
Result: Current page is not changed, input is clear

**Comment by dsanko-sc** [comment]
Refactored.

**Comment by asergeev-sc** [comment]
Please, reconfigure build process in a way that static site on **gh-pages** branch is generated for each branch, like it is done in
- https://github.com/OpusCapita/react-dates
- https://github.com/OpusCapita/react-crudeditor

**Comment by dsanko-sc** [comment]
Completed.
Link for testing: https://opuscapita.github.io/react-reference-select//branches/issue-25(slash)pagination-input/index.html?currentComponentName=ExampleInput&showSidebar=true

**Comment by nstoliar-sc** [comment]
Switching of pages doesn't work in IE. It is impossible to change page using manual page input or clicking on appropriate page number or 'previous'/'next' arrow. Spent 0.5 hour. 
![159](https://user-images.githubusercontent.com/25082017/38369648-e8bd63b0-38f0-11e8-97c1-5731abf13b6b.png)

**Comment by dsanko-sc** [comment]
Please, release it with version 2.1.0
