### ISSUE TITLE
Error appers while opening of react reference select in IE

### ISSUE THREAD

**Issue by nstoliar-sc** [OpusCapita/react-reference-select#27]
If react reference select is opened in IE, "SCRIPT5009: 'Promise' is undefined" error appears.

![160](https://user-images.githubusercontent.com/25082017/38372327-35db5d04-38f7-11e8-89d9-d439e31650c9.png)

**Comment by estambakio-sc** [comment]
[Demo for QA](https://opuscapita.github.io/react-reference-select/branches/master/?currentComponentName=ExampleInput)

Components to test: `ExampleInput`, `ReferenceAutocomplete`
Browser: IE11
