### ISSUE TITLE
Paging elements are not hidden for react reference search if 'all' items per page are selected

### ISSUE THREAD

**Issue by nstoliar-sc** [OpusCapita/react-reference-select#31]
Meta-Info | Value
-- | --
ExtProjectId | JCCMMN-01
Original Estimation | 4h
Remaining Estimation | 0h

If user selects count of elements per page more than common count of found elements, paging elements are hidden. But if user selects 'all', paging arrows and manual page input are not hidden: 

![167](https://user-images.githubusercontent.com/25082017/39628830-f3ea6016-4fb2-11e8-9b28-b6d003fb0050.png)

https://opuscapita.github.io/react-reference-select/?currentComponentName=ExampleInput

**Comment by estambakio-sc** [comment]
[Demo link](https://opuscapita.github.io/react-reference-select/branches/master/?currentComponentName=ExampleInput)

**Comment by nstoliar-sc** [comment]
Tested. Paging elements are hidden for react reference search if 'all' item per page is selected. Please, merge with master branch. Spent 0.5 hours.
