### ISSUE TITLE
When user opens reference search dialog, focus should be set on the first available search field

### ISSUE THREAD

**Issue by asergeev-sc** [OpusCapita/react-reference-select#32]
Meta-Info | Value
-- | --
ExtProjectId | JCCMMN-01
Original Estimation | 4h
Remaining Estimation | 0h

**Comment by estambakio-sc** [comment]
QA: this issue is tested in scope of https://github.com/OpusCapita/minsk-core-externals/issues/142 and https://github.com/OpusCapita/minsk-core-externals/issues/143

**Comment by nstoliar-sc** [comment]
Tested. Focus of cursor is set on the first available search field while opening of Reference Search pop-up. Please, merge with master branch. Spent 0,5 hour.
