### ISSUE TITLE
Wrong direction of sorting while clicking on arrow in reference search

### ISSUE THREAD

**Issue by nstoliar-sc** [OpusCapita/react-reference-select#33]
Meta-Info | Value
-- | --
ExtProjectId | JCCMMN-01
Original Estimation | ???h
Remaining Estimation | ???h

1. Open reference rearch (e.g. Search for Addresses);
2. click on name of first column -> all items is ascending sorted in first column
3. click on name of other column -> all items is descending sorted in selected column
Expected result: if user clicks first time on column name of each column, all items are ascending sorted in this column.

**Comment by estambakio-sc** [comment]
QA: this issue is tested in scope of https://github.com/OpusCapita/minsk-core-externals/issues/142 and https://github.com/OpusCapita/minsk-core-externals/issues/143

**Comment by nstoliar-sc** [comment]
Tested. Sorting in each column is sorted by ascending while first clicking on column name. Please, merge with master branch. Spent 0,5 hour.
