### ISSUE TITLE
Upgrade react-select dependency

### ISSUE THREAD

**Issue by ddivin-sc** [OpusCapita/react-reference-select#36]
Meta-Info | Value
-- | --
ExtProjectId | JCPIM-01.3
Original Estimation | 12h
Remaining Estimation | ???h

Old version react-select has a problem with close drop down. Fortunately, this is already fixed and available in the new version.

To do:
Need to migrate all reference select inputs of new API version 2.0.9 usage https://github.com/OpusCapita/react-select

Original issue https://github.com/OpusCapita/minsk-core-externals/issues/264

**Comment by ddivin-sc** [comment]
For QA: you can check it on eProc and PIM line branches

On eProc line branch need to check reference searches for (domain-core, organization, product-catalog, business-partner, classification, contract)
https://demo.core.dev.opuscapita.com/minsk-core-demo/react-reference-select-issue-3

On PIM line branch need to check reference searches for (attribute, boilerplate, business-partner, classification, contract, domain-core, product-catalog, organization, value-list, product-support)
https://demo.core.dev.opuscapita.com/minsk-core-demo/react-reference-select-issue-36-2

**Comment by ddivin-sc** [comment]
Please, review my changes

Related changes:

eProc line branches
https://github.com/OpusCapita/grails-domain-core/pull/26
https://github.com/OpusCapita/grails-organization/pull/31
https://github.com/OpusCapita/grails-product-catalog/pull/24
https://github.com/OpusCapita/grails-business-partner/pull/33
https://github.com/OpusCapita/grails-classification/pull/52
https://github.com/OpusCapita/grails-contract/pull/24

PIM line branches
https://github.com/OpusCapita/grails-attribute/pull/23
https://github.com/OpusCapita/grails-boilerplate/pull/94
https://github.com/OpusCapita/grails-business-partner/pull/34
https://github.com/OpusCapita/grails-classification/pull/53
https://github.com/OpusCapita/grails-contract/pull/25
https://github.com/OpusCapita/grails-domain-core/pull/27
https://github.com/OpusCapita/grails-product-catalog/pull/25
https://github.com/OpusCapita/grails-organization/pull/32
https://github.com/OpusCapita/grails-value-list/pull/13
https://github.com/OpusCapita/grails-product-support/pull/18

**Comment by asergeev-sc** [comment]
We need to release a new incompatible version 3.0.0. And write down complete release notes that should be visible for everyone.

**Comment by nstoliar-sc** [comment]
If React Inputs has icon for opening Reference Search and window has small size, icons for opening drop-down and cleaning filled move to left side of input. It is reproduced for Chrome and FF.

![406](https://user-images.githubusercontent.com/25082017/53818692-8830c100-3f79-11e9-8e6a-988bc56a2773.png)
