### ISSUE TITLE
In case when multi is set to true, then reference search selection should be used for updating (not replacing) values in input field

### ISSUE THREAD

**Issue by asergeev-sc** [OpusCapita/react-reference-select#37]
Meta-Info | Value
-- | --
ExtProjectId | OC-01.1.8
Original Estimation | 4h
Remaining Estimation | 4h

**Comment by dsanko-sc** [comment]
Completed.

**Comment by asergeev-sc** [comment]
https://github.com/OpusCapita/react-reference-select/blob/gh-pages/branches/issue-37/index.html - functionality does not work.
Popup dialog should provide perform a selection, not is shows values that are selected in input (THIS is not needed). Se for example how contract domain object select input/dialog works [here](https://demo.core.dev.opuscapita.com/minsk-core-demo/master/test/contractInputs)

**Comment by nstoliar-sc** [comment]
Tested. Selected values in input field are not removed after selecting new values via reference search. Input field is updated by new values. Please, merge with master branch.
