### ISSUE TITLE
Drop React v. 0.14.x support, use v. "^15.6.2 || ^16.2.0" as peer dependency 

### ISSUE THREAD

**Issue by asergeev-sc** [OpusCapita/react-reference-select#4]
As real dev dependency for test/demo purposes please, use, React v. 15.6.2 or higher.
After the changes increment a major number in module version.

See https://github.com/orgs/OpusCapita/teams/scand_core/discussions/2

**Comment by kvolkovich-sc** [comment]
Done: https://github.com/OpusCapita/react-reference-select/pull/8
