### ISSUE TITLE
Nested reference search form submit also submits all other forms at the page.

### ISSUE THREAD

**Issue by ddivin-sc** [OpusCapita/react-reference-select#40]
Meta-Info | Value
-- | --
ExtProjectId | JCPIM-01.3
Original Estimation | 2h
Remaining Estimation | ???h

ReferenceSearchDialog is not compatible with `redux-forms`, because the dialog rendered children form which submit parent.

### Solution
You should use [React Portal](https://reactjs.org/docs/portals.html) for render ReferenceSearchDialog to root body in ReferenceSearchInput component

Original issue: https://github.com/OpusCapita/minsk-core-externals/issues/269

**Comment by ddivin-sc** [comment]
For QA: please, test it on https://opuscapita.github.io/react-reference-select/branches/issue-40/

**Comment by nstoliar-sc** [comment]
Error "SCRIPT438: Object doesn't support property or method 'includes'" appears while searching in IE 11.
![417](https://user-images.githubusercontent.com/25082017/55623289-3fa03980-57ab-11e9-9201-ffc996de603a.png)

**Comment by ddivin-sc** [comment]
Examples for IE11 was fixed.

**Comment by nstoliar-sc** [comment]
Tested. Search of items is made correctly in reference search. Please, merge with master branch.
