### ISSUE TITLE
Placeholder for empty search result in select input has not German translation

### ISSUE THREAD

**Issue by nstoliar-sc** [OpusCapita/react-reference-select#43]
Meta-Info | Value
-- | --
ExtProjectId | JCPIM-01.3
Original Estimation | ???h
Remaining Estimation | ???h

Placeholders of select inputs of Boilerplate Editor have not German translations.

![8](https://user-images.githubusercontent.com/25082017/61056022-58983680-a3fb-11e9-9bfe-9bd91665929b.png)

![9](https://user-images.githubusercontent.com/25082017/61056029-5c2bbd80-a3fb-11e9-9c42-485c585575be.png)

![10](https://user-images.githubusercontent.com/25082017/61056034-5f26ae00-a3fb-11e9-8c8b-c2433c0ba1db.png)

![11](https://user-images.githubusercontent.com/25082017/61056046-62ba3500-a3fb-11e9-9995-cd8aab41c812.png)

![12](https://user-images.githubusercontent.com/25082017/61056051-65b52580-a3fb-11e9-94c7-392ad61e558c.png)

![13](https://user-images.githubusercontent.com/25082017/61056083-6a79d980-a3fb-11e9-8e77-8d59a28237da.png)

![14](https://user-images.githubusercontent.com/25082017/61056104-706fba80-a3fb-11e9-9d5b-a0c87c5259a3.png)

![15](https://user-images.githubusercontent.com/25082017/61056111-72d21480-a3fb-11e9-9a28-130401de3778.png)

![16](https://user-images.githubusercontent.com/25082017/61056118-75346e80-a3fb-11e9-82b4-3834239a2082.png)

![17](https://user-images.githubusercontent.com/25082017/61056132-7796c880-a3fb-11e9-861d-ec73f9e23444.png)

![18](https://user-images.githubusercontent.com/25082017/61056138-7a91b900-a3fb-11e9-8de0-4930f2d1d982.png)

**Comment by dsanko-sc** [comment]
Moved to https://github.com/OpusCapita/grails-boilerplate/issues/107.
