### ISSUE TITLE
Add possibility to configure custom search component

### ISSUE THREAD

**Issue by dsanko-sc** [OpusCapita/react-reference-select#44]
Meta-Info | Value
-- | --
ExtProjectId | JCPIM-01.3
Original Estimation | 2h
Remaining Estimation | 2h

Add possibility to configure custom search component.

Original issue: https://github.com/OpusCapita/minsk-core-externals/issues/355

**Comment by dsanko-sc** [comment]
Completed.
War file: com/jcatalog/test/jcdemo/8.12.GA-attribute-issue-27-SNAPSHOT/jcdemo-8.12.GA-attribute-issue-27-20190802.163202-1.war
Link: https://demo.core.dev.opuscapita.com/minsk-core-demo/attribute-issue-27

**Comment by asergeev-sc** [comment]
See my comments in [PR](https://github.com/OpusCapita/react-reference-select/pull/45#pullrequestreview-270603399)
