### ISSUE TITLE
Provide API to customize styles for options in ReactAutocomplete

### ISSUE THREAD

**Issue by ddivin-sc** [OpusCapita/react-reference-select#51]
Meta-Info | Value
-- | --
ExtProjectId | JCPIM-01.3
Original Estimation | ???h
Remaining Estimation | ???h

Description
---
The component should provide API to customize styles for options in ReactAutocomplete

For example: inactive options should be look like highlighted
![image](https://user-images.githubusercontent.com/25082763/69229375-5ce91300-0b96-11ea-959e-0c2eb37b78e8.png)

Solution
---
Provide custom styles properties that override styles in react-select, for example
```
<ReferenceAutocomplete
  autocompleteAction={(input) => {
    return new Promise((resolve) => {
      var options = [{"id": "1", "_objectLabel": "A"}, {"id": "2", "_objectLabel": "B", inactive: true}, {"id": "3", "_objectLabel": "C"}];
      resolve(options.filter((item) => item._objectLabel.toLowerCase().includes(input.toLowerCase())!== -1));
    });
  }}
  styles={{option: (provided, {data} ) => {
    const customStyles = {}
    if (data.inactive) {
        customStyles.backgroundColor = "#ccc"
        customStyles.color = "white"
    }
    return {
      ...provided,
      ...customStyles
    }
  }}}
  value={{"id": "1", "_objectLabel": "A"}}
  labelProperty="_objectLabel"
  valueProperty="id"
/>
```

See also: https://react-select.com/styles

Original issue: https://github.com/OpusCapita/minsk-core-externals/issues/494

**Comment by ddivin-sc** [comment]
Please, review my changes.

**Comment by asergeev-sc** [comment]
Property 'multiValueLabel' would be fully replaced is it is defined by the user. I propose to use composition, so user still overrides styles provided by react-select and our Reference Autocomplete component. E.g. something like this:

```js
    var {
        multiValueLabel: customMultiValueLabel = (provided, state) => provided, 
        ...otherStyles
    } = styles;
    
    const defaultMultiValueLabel = (provided, state) => {
      const rMargin = 150;
      const defaultMinWidth = 200;
      const { width = (rMargin + defaultMinWidth) } = this.props;
      const maxWidth = Math.max(width - rMargin, defaultMinWidth);

      return {
        ...provided,
        maxWidth: `${maxWidth}px`,
      }
    };
    
    //...
    
    styles: {
        otherStyles,
        multiValueLabel: (provided, state) => {
          customMultiValueLabel(defaultMultiValueLabel(provided, state), state)  
        } 
    }
```

**Comment by ddivin-sc** [comment]
For QA: you can test it on https://opuscapita.github.io/react-reference-select/branches/issue-51/?currentComponentName=ReferenceAutocomplete&showSidebar=true

**Comment by nstoliar-sc** [comment]
Tested. Appropriate style for specific option in reference autocomplete list was added. Please, merge with master branch.
