### ISSUE TITLE
Add possibility to configure default sorting order for reference search dialog

### ISSUE THREAD

**Issue by dsanko-sc** [OpusCapita/react-reference-select#54]
Meta-Info | Value
-- | --
ExtProjectId | JCPROC-01
Original Estimation | ???h
Remaining Estimation | ???h

When opening result reference search result dialog there is no indicator (an arrow) near the column which was used for sorting in a controller. 

E.g. on the screenshot the result is sorting by *createdOn* field. But the indicator (an arrow) is not shown when a user opens the dialog for the first time. 
![indicator](https://user-images.githubusercontent.com/29278135/80198997-8288b580-8629-11ea-8030-23d699a5b028.png)

Original issue: https://github.com/OpusCapita/minsk-core-externals/issues/626

**Comment by dsanko-sc** [comment]
Completed.
https://opuscapita.github.io/react-reference-select/branches/issue-54/?currentComponentName=ExampleInput

**Comment by nstoliar-sc** [comment]
Tested. If search result in reference search is sorted by some column, appropriate indicate icon (arrow) is displayed. Please, merge with master branch.
